"""OmniResearch contracts — typed Pydantic v2 models for inter-agent communication."""

from omni_contracts.enums import (
    ClaimStatus,
    FailureClass,
    MemoryEventType,
    SessionStatus,
    TaskStatus,
    TaskType,
    VerificationVerdict,
    WorkflowEventType,
)
from omni_contracts.models import (
    AgentResult,
    AnalysisFacts,
    BudgetConfig,
    Claim,
    ClaimEvidence,
    ContractModel,
    DatasetRef,
    DatasetSpec,
    Evidence,
    EvidencePack,
    ExperimentSpec,
    FailureRecord,
    GroundedAnswer,
    MemoryEvent,
    ModelSpec,
    NumericBinding,
    Plan,
    PlanDelta,
    PlanTask,
    ReplicationTarget,
    ResearchSpec,
    VerificationFinding,
    VerificationReport,
    WorkflowEvent,
)

__all__ = [
    # Enums
    "ClaimStatus",
    "FailureClass",
    "MemoryEventType",
    "SessionStatus",
    "TaskStatus",
    "TaskType",
    "VerificationVerdict",
    "WorkflowEventType",
    # Models
    "AgentResult",
    "AnalysisFacts",
    "BudgetConfig",
    "Claim",
    "ClaimEvidence",
    "ContractModel",
    "DatasetRef",
    "DatasetSpec",
    "Evidence",
    "EvidencePack",
    "ExperimentSpec",
    "FailureRecord",
    "GroundedAnswer",
    "MemoryEvent",
    "ModelSpec",
    "NumericBinding",
    "Plan",
    "PlanDelta",
    "PlanTask",
    "ReplicationTarget",
    "ResearchSpec",
    "VerificationFinding",
    "VerificationReport",
    "WorkflowEvent",
]
