"""Enumerations for OmniResearch contracts."""

from enum import StrEnum, unique


@unique
class SessionStatus(StrEnum):
    """Research session lifecycle states."""

    INIT = "INIT"
    PLAN = "PLAN"
    RESEARCH = "RESEARCH"
    DATASET = "DATASET"
    EXPERIMENT = "EXPERIMENT"
    ANALYSIS = "ANALYSIS"
    VERIFY = "VERIFY"
    REPORT = "REPORT"
    COMPLETE = "COMPLETE"
    PAUSED = "PAUSED"
    NEEDS_HUMAN = "NEEDS_HUMAN"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


@unique
class TaskType(StrEnum):
    """Types of tasks in a research plan DAG."""

    LITERATURE_REVIEW = "LITERATURE_REVIEW"
    DATASET_DISCOVERY = "DATASET_DISCOVERY"
    METHODOLOGY_SELECTION = "METHODOLOGY_SELECTION"
    EXPERIMENT_DESIGN = "EXPERIMENT_DESIGN"
    EXPERIMENT_EXECUTION = "EXPERIMENT_EXECUTION"
    RESULT_ANALYSIS = "RESULT_ANALYSIS"
    VERIFICATION = "VERIFICATION"
    REPORT = "REPORT"


@unique
class TaskStatus(StrEnum):
    """Task lifecycle states."""

    PENDING = "PENDING"
    RUNNING = "RUNNING"
    COMPLETED = "COMPLETED"
    FAILED = "FAILED"
    SKIPPED = "SKIPPED"
    CANCELLED = "CANCELLED"


@unique
class FailureClass(StrEnum):
    """Classified failure types with allowed repairs."""

    CODE_ERROR = "CODE_ERROR"
    RESOURCE_ERROR = "RESOURCE_ERROR"
    MISSING_DEPENDENCY = "MISSING_DEPENDENCY"
    DATA_ISSUE = "DATA_ISSUE"
    EVIDENCE_INSUFFICIENT = "EVIDENCE_INSUFFICIENT"
    NUMBER_MISMATCH = "NUMBER_MISMATCH"
    UNSUPPORTED_CLAIM = "UNSUPPORTED_CLAIM"
    DISCREPANCY_WITH_PUBLISHED = "DISCREPANCY_WITH_PUBLISHED"
    INVALID_COMPARISON = "INVALID_COMPARISON"
    TOOL_UNAVAILABLE = "TOOL_UNAVAILABLE"


@unique
class ClaimStatus(StrEnum):
    """Claim verification status."""

    PENDING = "PENDING"
    VERIFIED = "VERIFIED"
    FAILED = "FAILED"
    WEAKENED = "WEAKENED"
    DROPPED = "DROPPED"


@unique
class VerificationVerdict(StrEnum):
    """Verification check outcomes."""

    SUPPORTED = "SUPPORTED"
    PARTIAL = "PARTIAL"
    UNSUPPORTED = "UNSUPPORTED"
    CONTRADICTED = "CONTRADICTED"
    ABSTAIN = "ABSTAIN"


@unique
class WorkflowEventType(StrEnum):
    """Types of workflow events in the outbox."""

    SESSION_CREATED = "SESSION_CREATED"
    SESSION_STATUS_CHANGED = "SESSION_STATUS_CHANGED"
    PLAN_CREATED = "PLAN_CREATED"
    PLAN_UPDATED = "PLAN_UPDATED"
    TASK_STARTED = "TASK_STARTED"
    TASK_COMPLETED = "TASK_COMPLETED"
    TASK_FAILED = "TASK_FAILED"
    PAPER_FOUND = "PAPER_FOUND"
    DATASET_SELECTED = "DATASET_SELECTED"
    EXPERIMENT_STARTED = "EXPERIMENT_STARTED"
    EXPERIMENT_COMPLETED = "EXPERIMENT_COMPLETED"
    RUN_STARTED = "RUN_STARTED"
    RUN_COMPLETED = "RUN_COMPLETED"
    ANALYSIS_COMPLETED = "ANALYSIS_COMPLETED"
    CLAIM_CREATED = "CLAIM_CREATED"
    VERIFICATION_STARTED = "VERIFICATION_STARTED"
    VERIFICATION_COMPLETED = "VERIFICATION_COMPLETED"
    REPLAN_TRIGGERED = "REPLAN_TRIGGERED"
    REPORT_GENERATED = "REPORT_GENERATED"
    BUDGET_WARNING = "BUDGET_WARNING"
    BUDGET_EXCEEDED = "BUDGET_EXCEEDED"
    HUMAN_INPUT_NEEDED = "HUMAN_INPUT_NEEDED"
    ERROR = "ERROR"


@unique
class MemoryEventType(StrEnum):
    """Types of memory events in the episodic ledger."""

    DECISION = "DECISION"
    FINDING = "FINDING"
    FAILURE = "FAILURE"
    PAPER_SELECTED = "PAPER_SELECTED"
    DATASET_SELECTED = "DATASET_SELECTED"
    EXPERIMENT_RESULT = "EXPERIMENT_RESULT"
    VERIFICATION_RESULT = "VERIFICATION_RESULT"
    PLAN_CHANGE = "PLAN_CHANGE"
    HUMAN_GUIDANCE = "HUMAN_GUIDANCE"
